### ISSUE TITLE
Unable to start project

### ISSUE THREAD

**Issue by gustavjf** [contentful-labs/guide-app#5]
Hello @contentful, I cloned your example recently and tried to run it but I was having some problems. I'm running OSX 10.10.2

I noticed the server would start, but when I pointed Chrome to `http://localhost:3010` I got the following warnings and errors:

```
connect deprecated methodOverride: use method-override npm module instead server.js:30:17
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
Warning: ReactAsync.renderComponentToStringWithAsyncState will be deprecated in a future version. Use ReactAsync.renderToStringAsync instead.
install fibers: npm install fibers
Error: Error transforming /Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/fibers/fibers.js to JSX: Error: Parse Error: Line 2: Illegal return statement
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/node-jsx/index.js:24:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at renderToStringAsync (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/react-async/index.js:73:17)
    at Object.renderComponentToStringWithAsyncState (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/react-async/index.js:110:10)
    at Object.handle (/Users/gustavojimenez/Projects/contentful-examples/guide-app/server.js:41:14)
    at next (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at pass (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/express/lib/router/index.js:110:24)
GET / 500 108.488 ms - -
install fibers: npm install fibers
Error: Error transforming /Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/fibers/fibers.js to JSX: Error: Parse Error: Line 2: Illegal return statement
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/node-jsx/index.js:24:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at renderToStringAsync (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/react-async/index.js:73:17)
    at Object.renderComponentToStringWithAsyncState (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/react-async/index.js:110:10)
    at Object.handle (/Users/gustavojimenez/Projects/contentful-examples/guide-app/server.js:41:14)
    at next (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at pass (/Users/gustavojimenez/Projects/contentful-examples/guide-app/node_modules/express/lib/router/index.js:110:24)
GET /favicon.ico 500 11.042 ms - -
```
I think I solved the problem though. You can see the changes I made here: https://github.com/gustavjf/guide-app/commits/master

Would you consider reviewing my changes for a pull request?

**Comment by trodrigues** [comment]
Hi there,

we're not really supporting or maintaining this project anymore as there's a new version at https://github.com/contentful-labs/guide-app-sw using a more recent version of React, and with a cleaner structure.

**Comment by gustavjf** [comment]
I see, I was pointed to this repo from the demos in the developers page.

https://www.contentful.com/developers/

I didn't realize there was an updated version, but good to know!
